# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  panda_joint1: -2.8973
  panda_joint2: -0.4381
  panda_joint3: -0.3805
  panda_joint4: -2.7925
  panda_joint5: -2.0159
  panda_joint6: 2.8849
  panda_joint7: 0.7452
